In [2]:
for i in range(100,97,-1):
  print(str(i) + " bottles of beer on the wall")
  print(str(i) + " bottles of beer")
  print(" take one down, pass it around,")
  print(str(i-1) + " bottles of beer on the wall")

100 bottles of beer on the wall
100 bottles of beer
 take one down, pass it around,
99 bottles of beer on the wall
99 bottles of beer on the wall
99 bottles of beer
 take one down, pass it around,
98 bottles of beer on the wall
98 bottles of beer on the wall
98 bottles of beer
 take one down, pass it around,
97 bottles of beer on the wall
100 bottles of beer on the wall
100 bottles of beer
 take one down, pass it around,
99 bottles of beer on the wall
99 bottles of beer on the wall
99 bottles of beer
 take one down, pass it around,
98 bottles of beer on the wall
98 bottles of beer on the wall
98 bottles of beer
 take one down, pass it around,
97 bottles of beer on the wall


In [4]:
def sing_verse(num):
  song = str(num) + " bottles of beer on the wall \n" + str(num) + " bottles of beer \n" + " take one down, pass it around, \n" + str(num-1) + " bottles of beer on the wall \n"
  
  return song

  #________

In [7]:
import numpy as np

In [8]:
a_vec = np.array([-2, 1, -3, -9, 7])

for val in a_vec:
  if val > 0:
    val = np.sqrt(val)
  print(val)

-2
1.0
-3
-9
2.6457513110645907
-2
1.0
-3
-9
2.6457513110645907


In [9]:
is_pos = a_vec > 0

a_vec[is_pos] = np.sqrt(a_vec[is_pos])

a_vec

array([-2,  1, -3, -9,  2])

In [14]:
#checkin 7.2 part 1 
def sqrt_pos_unvec(value):
    if value > 0:
        return np.sqrt(value)
    else:
        return value

new_vec = []

for val in a_vec:
    new_vec.append(sqrt_pos_unvec(val))

new_vec

[-2, 1.0, -3, -9, 1.4142135623730951]

In [16]:
#checkin 7.2 part 2
def sqrt_pos_vec(value):
    is_pos = value > 0
    value[is_pos] = np.sqrt(value[is_pos])
    return value

print(a_vec)
print(sqrt_pos_vec(a_vec))

[-2  1 -3 -9  2]
[-2  1 -3 -9  1]
[-2  1 -3 -9  2]
[-2  1 -3 -9  1]


In [2]:
def sing_verse(num):
  song = str(num) + " bottles of beer on the wall \n" + str(num) + " bottles of beer \n" + " take one down, pass it around, \n" + str(num-1) + " bottles of beer on the wall \n"
  
  return song

In [3]:
song = ""

for i in range(100,97,-1):
  song = song + sing_verse(i)
  
print(song)

100 bottles of beer on the wall 
100 bottles of beer 
 take one down, pass it around, 
99 bottles of beer on the wall 
99 bottles of beer on the wall 
99 bottles of beer 
 take one down, pass it around, 
98 bottles of beer on the wall 
98 bottles of beer on the wall 
98 bottles of beer 
 take one down, pass it around, 
97 bottles of beer on the wall 

100 bottles of beer on the wall 
100 bottles of beer 
 take one down, pass it around, 
99 bottles of beer on the wall 
99 bottles of beer on the wall 
99 bottles of beer 
 take one down, pass it around, 
98 bottles of beer on the wall 
98 bottles of beer on the wall 
98 bottles of beer 
 take one down, pass it around, 
97 bottles of beer on the wall 



In [4]:
#7.31 mapping 
song = map(sing_verse, range(100, 97, -1))
song = list(song)
print("".join(song))

100 bottles of beer on the wall 
100 bottles of beer 
 take one down, pass it around, 
99 bottles of beer on the wall 
99 bottles of beer on the wall 
99 bottles of beer 
 take one down, pass it around, 
98 bottles of beer on the wall 
98 bottles of beer on the wall 
98 bottles of beer 
 take one down, pass it around, 
97 bottles of beer on the wall 

100 bottles of beer on the wall 
100 bottles of beer 
 take one down, pass it around, 
99 bottles of beer on the wall 
99 bottles of beer on the wall 
99 bottles of beer 
 take one down, pass it around, 
98 bottles of beer on the wall 
98 bottles of beer on the wall 
98 bottles of beer 
 take one down, pass it around, 
97 bottles of beer on the wall 

